name: Pytest
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install uv
        python -m uv pip install --upgrade pip
        python -m uv pip install torch==2.3.1
        python -m uv pip install -e .[test]
    - name: Test with pytest
      run: |
        python -m pytest  tests/
